version: '3.6'

services:
  postgres:
    image: postgres:latest
    restart: on-failure
    hostname: postgres
    environment:
      - POSTGRES_DB=itaudb
      - POSTGRES_USER=userdb
      - POSTGRES_PASSWORD=pass
    ports:
      - "5432:5432"
    volumes:
      - ./docker-volumes/dbconfig/schema.sql:/docker-entrypoint-initdb.d/schema.sql
    networks:
      - local

  redis:
    image: redis/redis-stack-server:latest
    ports:
      - 6379:6379
    volumes:
      - ./docker-volumes/redis_data:/data
    networks:
      - local


  json_server:
    image: clue/json-server
    restart: on-failure
    ports:
      - 8090:80
    volumes:
      - ./docker-volumes/fake-api/db.json:/data/db.json
    networks:
      - local

networks:
  local:
    driver: bridge